#pragma once


#include "Basic.h"

#include "Pointer.h"
#include "String.h"
#include "Console.h"
#include "Exception.h"
#include "Locale.h"
#include "GlobalStorage.h"
#include "Locale.h"
#include "Threading.h"
#include "HttpUtility.h"
#include "system.h"
#include "NVariant.h"

#include ".\FileSystem\Folder.h"
#include ".\FileSystem\file.h"
#include ".\FileSystem\FilePath.h"
#include ".\FileSystem\FileInfo.h"

#include ".\Stream\Interfaces.h"
#include ".\Stream\Accessor.h"
#include ".\Stream\BroadcastStream.h"
#include ".\Stream\CharFormat.h"
#include ".\Stream\CacheStream.h"
#include ".\Stream\FileStream.h"
#include ".\Stream\memorystream.h"
#include ".\Stream\recorderstream.h"
#include ".\Stream\CompressionStream.h"

#include ".\Collections\interfaces.h"
#include ".\Collections\Pair.h"
#include ".\Collections\List.h"
#include ".\Collections\Dictionary.h"
#include ".\Collections\Operation.h"
#include ".\Collections\OperationCopyFrom.h"
#include ".\Collections\OperationForEach.h"
#include ".\Collections\OperationString.h"
#include ".\Collections\OperationEnumerable.h"
#include ".\Collections\OperationSequence.h"

#include ".\Regex\Regex.h"
#include ".\Regex\RegexAutomaton.h"
#include ".\Regex\RegexData.h"
#include ".\Regex\RegexExpression.h"
#include ".\Regex\RegexWriter.h"
#include ".\Regex\RegexPure.h"
#include ".\Regex\RegexRich.h"

#include ".\UnitTest\UnitTest.h"